name: numpy-tutorials
channels:
  - conda-forge
dependencies:
  # For running the tutorials
  - numpy
  - scipy
  - matplotlib
  - pandas 
  - statsmodels
  - imageio
  # For building the site
  - sphinx<5
  - myst-nb
  - sphinx-book-theme
  - sphinx-copybutton
