name: numpy-tutorials
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pytest
  - nbval
  - statsmodels
  - pip
  - imageio
  - pip:
    - jupyter-book
    - gym[atari]

