name: numpy-tutorials
channels:
  - conda-forge
dependencies:
  # For running the tutorials
  - numpy
  - scipy
  - matplotlib
  - pandas 
  - statsmodels
  - pip
  - imageio
  - pooch
  - ffmpeg  # For gym/atari
  # For building the site
  - sphinx
  - myst-nb
  - sphinx-book-theme
  - sphinx-copybutton
  - pip:
    - gym[atari]==0.19
