name: numpy-tutorials
channels:
  - conda-forge
dependencies:
  # For running the tutorials
  - numpy
  - scipy
  - pooch
  - matplotlib
  - pandas
  - imageio
  # For building the site
  - tox
  - jupytext
  - pip
  - pip:
    - jupyter-book>=2
    - jupyterlab_myst
